// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameInfo.proto

package org.robocup_logistics.llsf_msgs;

public final class GameInfoProtos {
  private GameInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GameInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string known_teams = 1;
    /**
     * <code>repeated string known_teams = 1;</code>
     *
     * <pre>
     * The new desired phase
     * </pre>
     */
    java.util.List<java.lang.String>
    getKnownTeamsList();
    /**
     * <code>repeated string known_teams = 1;</code>
     *
     * <pre>
     * The new desired phase
     * </pre>
     */
    int getKnownTeamsCount();
    /**
     * <code>repeated string known_teams = 1;</code>
     *
     * <pre>
     * The new desired phase
     * </pre>
     */
    java.lang.String getKnownTeams(int index);
    /**
     * <code>repeated string known_teams = 1;</code>
     *
     * <pre>
     * The new desired phase
     * </pre>
     */
    com.google.protobuf.ByteString
        getKnownTeamsBytes(int index);
  }
  /**
   * Protobuf type {@code llsf_msgs.GameInfo}
   *
   * <pre>
   * Game information for controllers
   * </pre>
   */
  public static final class GameInfo extends
      com.google.protobuf.GeneratedMessage
      implements GameInfoOrBuilder {
    // Use GameInfo.newBuilder() to construct.
    private GameInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameInfo defaultInstance;
    public static GameInfo getDefaultInstance() {
      return defaultInstance;
    }

    public GameInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                knownTeams_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              knownTeams_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          knownTeams_ = new com.google.protobuf.UnmodifiableLazyStringList(knownTeams_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.GameInfoProtos.internal_static_llsf_msgs_GameInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.GameInfoProtos.internal_static_llsf_msgs_GameInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo.class, org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<GameInfo> PARSER =
        new com.google.protobuf.AbstractParser<GameInfo>() {
      public GameInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameInfo> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code llsf_msgs.GameInfo.CompType}
     */
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>COMP_ID = 2000;</code>
       */
      COMP_ID(0, 2000),
      /**
       * <code>MSG_TYPE = 81;</code>
       */
      MSG_TYPE(1, 81),
      ;

      /**
       * <code>COMP_ID = 2000;</code>
       */
      public static final int COMP_ID_VALUE = 2000;
      /**
       * <code>MSG_TYPE = 81;</code>
       */
      public static final int MSG_TYPE_VALUE = 81;


      public final int getNumber() { return value; }

      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 81: return MSG_TYPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompType[] VALUES = values();

      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:llsf_msgs.GameInfo.CompType)
    }

    // repeated string known_teams = 1;
    public static final int KNOWN_TEAMS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList knownTeams_;
    /**
     * <code>repeated string known_teams = 1;</code>
     *
     * <pre>
     * The new desired phase
     * </pre>
     */
    public java.util.List<java.lang.String>
        getKnownTeamsList() {
      return knownTeams_;
    }
    /**
     * <code>repeated string known_teams = 1;</code>
     *
     * <pre>
     * The new desired phase
     * </pre>
     */
    public int getKnownTeamsCount() {
      return knownTeams_.size();
    }
    /**
     * <code>repeated string known_teams = 1;</code>
     *
     * <pre>
     * The new desired phase
     * </pre>
     */
    public java.lang.String getKnownTeams(int index) {
      return knownTeams_.get(index);
    }
    /**
     * <code>repeated string known_teams = 1;</code>
     *
     * <pre>
     * The new desired phase
     * </pre>
     */
    public com.google.protobuf.ByteString
        getKnownTeamsBytes(int index) {
      return knownTeams_.getByteString(index);
    }

    private void initFields() {
      knownTeams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < knownTeams_.size(); i++) {
        output.writeBytes(1, knownTeams_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < knownTeams_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(knownTeams_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getKnownTeamsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code llsf_msgs.GameInfo}
     *
     * <pre>
     * Game information for controllers
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.GameInfoProtos.internal_static_llsf_msgs_GameInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.GameInfoProtos.internal_static_llsf_msgs_GameInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo.class, org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        knownTeams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.GameInfoProtos.internal_static_llsf_msgs_GameInfo_descriptor;
      }

      public org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo.getDefaultInstance();
      }

      public org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo build() {
        org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo buildPartial() {
        org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo result = new org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          knownTeams_ = new com.google.protobuf.UnmodifiableLazyStringList(
              knownTeams_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.knownTeams_ = knownTeams_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo other) {
        if (other == org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo.getDefaultInstance()) return this;
        if (!other.knownTeams_.isEmpty()) {
          if (knownTeams_.isEmpty()) {
            knownTeams_ = other.knownTeams_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureKnownTeamsIsMutable();
            knownTeams_.addAll(other.knownTeams_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.GameInfoProtos.GameInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string known_teams = 1;
      private com.google.protobuf.LazyStringList knownTeams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureKnownTeamsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          knownTeams_ = new com.google.protobuf.LazyStringArrayList(knownTeams_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string known_teams = 1;</code>
       *
       * <pre>
       * The new desired phase
       * </pre>
       */
      public java.util.List<java.lang.String>
          getKnownTeamsList() {
        return java.util.Collections.unmodifiableList(knownTeams_);
      }
      /**
       * <code>repeated string known_teams = 1;</code>
       *
       * <pre>
       * The new desired phase
       * </pre>
       */
      public int getKnownTeamsCount() {
        return knownTeams_.size();
      }
      /**
       * <code>repeated string known_teams = 1;</code>
       *
       * <pre>
       * The new desired phase
       * </pre>
       */
      public java.lang.String getKnownTeams(int index) {
        return knownTeams_.get(index);
      }
      /**
       * <code>repeated string known_teams = 1;</code>
       *
       * <pre>
       * The new desired phase
       * </pre>
       */
      public com.google.protobuf.ByteString
          getKnownTeamsBytes(int index) {
        return knownTeams_.getByteString(index);
      }
      /**
       * <code>repeated string known_teams = 1;</code>
       *
       * <pre>
       * The new desired phase
       * </pre>
       */
      public Builder setKnownTeams(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKnownTeamsIsMutable();
        knownTeams_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string known_teams = 1;</code>
       *
       * <pre>
       * The new desired phase
       * </pre>
       */
      public Builder addKnownTeams(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKnownTeamsIsMutable();
        knownTeams_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string known_teams = 1;</code>
       *
       * <pre>
       * The new desired phase
       * </pre>
       */
      public Builder addAllKnownTeams(
          java.lang.Iterable<java.lang.String> values) {
        ensureKnownTeamsIsMutable();
        super.addAll(values, knownTeams_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string known_teams = 1;</code>
       *
       * <pre>
       * The new desired phase
       * </pre>
       */
      public Builder clearKnownTeams() {
        knownTeams_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string known_teams = 1;</code>
       *
       * <pre>
       * The new desired phase
       * </pre>
       */
      public Builder addKnownTeamsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKnownTeamsIsMutable();
        knownTeams_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:llsf_msgs.GameInfo)
    }

    static {
      defaultInstance = new GameInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.GameInfo)
  }

  public interface SetTeamNameOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string team_name = 1;
    /**
     * <code>required string team_name = 1;</code>
     *
     * <pre>
     * Name of the team to set
     * </pre>
     */
    boolean hasTeamName();
    /**
     * <code>required string team_name = 1;</code>
     *
     * <pre>
     * Name of the team to set
     * </pre>
     */
    java.lang.String getTeamName();
    /**
     * <code>required string team_name = 1;</code>
     *
     * <pre>
     * Name of the team to set
     * </pre>
     */
    com.google.protobuf.ByteString
        getTeamNameBytes();

    // required .llsf_msgs.Team team_color = 2;
    /**
     * <code>required .llsf_msgs.Team team_color = 2;</code>
     *
     * <pre>
     * Color of team
     * </pre>
     */
    boolean hasTeamColor();
    /**
     * <code>required .llsf_msgs.Team team_color = 2;</code>
     *
     * <pre>
     * Color of team
     * </pre>
     */
    org.robocup_logistics.llsf_msgs.TeamProtos.Team getTeamColor();
  }
  /**
   * Protobuf type {@code llsf_msgs.SetTeamName}
   *
   * <pre>
   * Request setting of a new game phase
   * </pre>
   */
  public static final class SetTeamName extends
      com.google.protobuf.GeneratedMessage
      implements SetTeamNameOrBuilder {
    // Use SetTeamName.newBuilder() to construct.
    private SetTeamName(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SetTeamName(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SetTeamName defaultInstance;
    public static SetTeamName getDefaultInstance() {
      return defaultInstance;
    }

    public SetTeamName getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SetTeamName(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              teamName_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.TeamProtos.Team value = org.robocup_logistics.llsf_msgs.TeamProtos.Team.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                teamColor_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.GameInfoProtos.internal_static_llsf_msgs_SetTeamName_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.GameInfoProtos.internal_static_llsf_msgs_SetTeamName_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName.class, org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName.Builder.class);
    }

    public static com.google.protobuf.Parser<SetTeamName> PARSER =
        new com.google.protobuf.AbstractParser<SetTeamName>() {
      public SetTeamName parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetTeamName(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SetTeamName> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code llsf_msgs.SetTeamName.CompType}
     */
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>COMP_ID = 2000;</code>
       */
      COMP_ID(0, 2000),
      /**
       * <code>MSG_TYPE = 82;</code>
       */
      MSG_TYPE(1, 82),
      ;

      /**
       * <code>COMP_ID = 2000;</code>
       */
      public static final int COMP_ID_VALUE = 2000;
      /**
       * <code>MSG_TYPE = 82;</code>
       */
      public static final int MSG_TYPE_VALUE = 82;


      public final int getNumber() { return value; }

      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 82: return MSG_TYPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompType[] VALUES = values();

      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:llsf_msgs.SetTeamName.CompType)
    }

    private int bitField0_;
    // required string team_name = 1;
    public static final int TEAM_NAME_FIELD_NUMBER = 1;
    private java.lang.Object teamName_;
    /**
     * <code>required string team_name = 1;</code>
     *
     * <pre>
     * Name of the team to set
     * </pre>
     */
    public boolean hasTeamName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string team_name = 1;</code>
     *
     * <pre>
     * Name of the team to set
     * </pre>
     */
    public java.lang.String getTeamName() {
      java.lang.Object ref = teamName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          teamName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string team_name = 1;</code>
     *
     * <pre>
     * Name of the team to set
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTeamNameBytes() {
      java.lang.Object ref = teamName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teamName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .llsf_msgs.Team team_color = 2;
    public static final int TEAM_COLOR_FIELD_NUMBER = 2;
    private org.robocup_logistics.llsf_msgs.TeamProtos.Team teamColor_;
    /**
     * <code>required .llsf_msgs.Team team_color = 2;</code>
     *
     * <pre>
     * Color of team
     * </pre>
     */
    public boolean hasTeamColor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .llsf_msgs.Team team_color = 2;</code>
     *
     * <pre>
     * Color of team
     * </pre>
     */
    public org.robocup_logistics.llsf_msgs.TeamProtos.Team getTeamColor() {
      return teamColor_;
    }

    private void initFields() {
      teamName_ = "";
      teamColor_ = org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTeamName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTeamColor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTeamNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, teamColor_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTeamNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, teamColor_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code llsf_msgs.SetTeamName}
     *
     * <pre>
     * Request setting of a new game phase
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamNameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.GameInfoProtos.internal_static_llsf_msgs_SetTeamName_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.GameInfoProtos.internal_static_llsf_msgs_SetTeamName_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName.class, org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        teamName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        teamColor_ = org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.GameInfoProtos.internal_static_llsf_msgs_SetTeamName_descriptor;
      }

      public org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName.getDefaultInstance();
      }

      public org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName build() {
        org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName buildPartial() {
        org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName result = new org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.teamName_ = teamName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.teamColor_ = teamColor_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName other) {
        if (other == org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName.getDefaultInstance()) return this;
        if (other.hasTeamName()) {
          bitField0_ |= 0x00000001;
          teamName_ = other.teamName_;
          onChanged();
        }
        if (other.hasTeamColor()) {
          setTeamColor(other.getTeamColor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTeamName()) {
          
          return false;
        }
        if (!hasTeamColor()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.GameInfoProtos.SetTeamName) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string team_name = 1;
      private java.lang.Object teamName_ = "";
      /**
       * <code>required string team_name = 1;</code>
       *
       * <pre>
       * Name of the team to set
       * </pre>
       */
      public boolean hasTeamName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string team_name = 1;</code>
       *
       * <pre>
       * Name of the team to set
       * </pre>
       */
      public java.lang.String getTeamName() {
        java.lang.Object ref = teamName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          teamName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string team_name = 1;</code>
       *
       * <pre>
       * Name of the team to set
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTeamNameBytes() {
        java.lang.Object ref = teamName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teamName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string team_name = 1;</code>
       *
       * <pre>
       * Name of the team to set
       * </pre>
       */
      public Builder setTeamName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        teamName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string team_name = 1;</code>
       *
       * <pre>
       * Name of the team to set
       * </pre>
       */
      public Builder clearTeamName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        teamName_ = getDefaultInstance().getTeamName();
        onChanged();
        return this;
      }
      /**
       * <code>required string team_name = 1;</code>
       *
       * <pre>
       * Name of the team to set
       * </pre>
       */
      public Builder setTeamNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        teamName_ = value;
        onChanged();
        return this;
      }

      // required .llsf_msgs.Team team_color = 2;
      private org.robocup_logistics.llsf_msgs.TeamProtos.Team teamColor_ = org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN;
      /**
       * <code>required .llsf_msgs.Team team_color = 2;</code>
       *
       * <pre>
       * Color of team
       * </pre>
       */
      public boolean hasTeamColor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .llsf_msgs.Team team_color = 2;</code>
       *
       * <pre>
       * Color of team
       * </pre>
       */
      public org.robocup_logistics.llsf_msgs.TeamProtos.Team getTeamColor() {
        return teamColor_;
      }
      /**
       * <code>required .llsf_msgs.Team team_color = 2;</code>
       *
       * <pre>
       * Color of team
       * </pre>
       */
      public Builder setTeamColor(org.robocup_logistics.llsf_msgs.TeamProtos.Team value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        teamColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .llsf_msgs.Team team_color = 2;</code>
       *
       * <pre>
       * Color of team
       * </pre>
       */
      public Builder clearTeamColor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        teamColor_ = org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:llsf_msgs.SetTeamName)
    }

    static {
      defaultInstance = new SetTeamName(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.SetTeamName)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_GameInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_GameInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_SetTeamName_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_SetTeamName_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016GameInfo.proto\022\tllsf_msgs\032\nTeam.proto\"" +
      "G\n\010GameInfo\022\023\n\013known_teams\030\001 \003(\t\"&\n\010Comp" +
      "Type\022\014\n\007COMP_ID\020\320\017\022\014\n\010MSG_TYPE\020Q\"m\n\013SetT" +
      "eamName\022\021\n\tteam_name\030\001 \002(\t\022#\n\nteam_color" +
      "\030\002 \002(\0162\017.llsf_msgs.Team\"&\n\010CompType\022\014\n\007C" +
      "OMP_ID\020\320\017\022\014\n\010MSG_TYPE\020RB1\n\037org.robocup_l" +
      "ogistics.llsf_msgsB\016GameInfoProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_llsf_msgs_GameInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_llsf_msgs_GameInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_llsf_msgs_GameInfo_descriptor,
              new java.lang.String[] { "KnownTeams", });
          internal_static_llsf_msgs_SetTeamName_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_llsf_msgs_SetTeamName_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_llsf_msgs_SetTeamName_descriptor,
              new java.lang.String[] { "TeamName", "TeamColor", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.robocup_logistics.llsf_msgs.TeamProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
